# Makefile — the visible command surface for the hidden .workspace/ control plane.
#
# MACHINERY: regenerated by create-git-workspace on every `update.sh`. Do not
# edit; add your own targets to a separate file.

SCRIPTS := .workspace/scripts

.DEFAULT_GOAL := help

.PHONY: help status bootstrap guard replan new-work run run-dry aggregate \
        add-repo delete-repo mute-repo

help: ## show this help
	@echo "git-workspace-test — workspace commands"
	@grep -hE '^[a-z][a-z-]*:.*## ' $(MAKEFILE_LIST) \
		| sort \
		| awk -F':.*## ' '{printf "  \033[1m%-12s\033[0m %s\n", $$1, $$2}'

status: ## branch + clean/dirty for every managed checkout
	@$(SCRIPTS)/status.sh

bootstrap: ## clone/attach every repo listed in .workspace/repos.yml
	@$(SCRIPTS)/bootstrap.sh

guard: ## fail if a child repo was staged into the wrapper index
	@$(SCRIPTS)/guard.sh

replan: ## redraft the workspace daily plan from project/tasks (draft only)
	@$(SCRIPTS)/replan.sh

new-work: ## show your new commits per repo since the last status run
	@python3 $(SCRIPTS)/new-work.py

aggregate: ## rebuild daily-plan-summary.md from .workspace/plans/
	@python3 $(SCRIPTS)/aggregate-plans.py

run: ## full status run: summarize, aggregate, advance state (uses claude -p)
	@python3 $(SCRIPTS)/run.py

run-dry: ## same, but with no LLM calls — deterministic placeholders
	@python3 $(SCRIPTS)/run.py --dry-run

# The repo verbs take arguments, and make reads bare words as extra goals — so
# they are passed through ARGS. The scripts are the real interface; these are a
# convenience. e.g. make add-repo ARGS="git@github.com:me/x.git --priority 1"
add-repo: ## register + clone a repo   ARGS="<url> [--name N] [--branch B] [--priority N]"
	@python3 $(SCRIPTS)/add-repo.py $(ARGS)

delete-repo: ## unregister a repo, refusing a dirty/unpushed checkout   ARGS="<name>"
	@python3 $(SCRIPTS)/delete-repo.py $(ARGS)

mute-repo: ## quiet a repo in the rollup   ARGS="<name> [--skip|--unmute]"
	@python3 $(SCRIPTS)/mute-repo.py $(ARGS)
