# Makefile — the visible command surface for the hidden .workspace/ control plane.
#
# MACHINERY: regenerated by create-git-workspace on every `update.sh`. Do not
# edit; add your own targets to a separate file.

SCRIPTS := .workspace/scripts

.DEFAULT_GOAL := help

.PHONY: help status bootstrap guard

help: ## show this help
	@echo "git-workspace-test — workspace commands"
	@grep -hE '^[a-z][a-z-]*:.*## ' $(MAKEFILE_LIST) \
		| sort \
		| awk -F':.*## ' '{printf "  \033[1m%-12s\033[0m %s\n", $$1, $$2}'

status: ## branch + clean/dirty for every managed checkout
	@$(SCRIPTS)/status.sh

bootstrap: ## clone/attach every repo listed in .workspace/repos.yml
	@$(SCRIPTS)/bootstrap.sh

guard: ## fail if a child repo was staged into the wrapper index
	@$(SCRIPTS)/guard.sh
